#!/bin/bash

CONFIG_SERVER_PASSWORD="my-password"
CONFIG_SERVER_USERNAME="my-username"
GATEWAY_SERVER_PORT=8003
EUREKA_URL="http://my-username:my-password@localhost:8001/eureka/"

IMAGE_NAME="api_gateway"

EXTERNAL_IP=$(hostname -I | awk '{print $1}')


docker run -d -p ${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT} \
  -e CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD} \
  -e CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME} \
  -e SERVER_PORT=${GATEWAY_SERVER_PORT} \
  -e EUREKA_URL=${EUREKA_URL} \
  -e EXTERNAL_IP=${EXTERNAL_IP} \
  ${IMAGE_NAME}